# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' windowThreshold Function
#'
#' @param meas_col the numeric column of the measure
#' @param meas_norm a numeric vector showing the c(low, high) acceptable range
#' @param time_col the time column, as a numeric
#' @param look_backward the amount to look backward for an invalid value
#' @param look_forward the amount to look forward for an invalid value
#'
#' @return logical vector for each row in the initial time row
#' @export
#'
#' @examples
#' d <- data.frame(
#' measure = 1:10,
#' time = 0:9
#' )
#' library(dplyr)
#' d %>% mutate(hit = windowThreshold(measure, c(2,8), time, 2, 0))
#'
#'
windowThreshold <- function(meas_col, meas_norm, time_col, look_backward, look_forward) {
    .Call('_vakdr_windowThreshold', PACKAGE = 'vakdr', meas_col, meas_norm, time_col, look_backward, look_forward)
}

